# Generated by Django 4.1.3 on 2022-11-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='название')),
                ('description_short', models.TextField(verbose_name='краткое описание')),
                ('description_long', models.TextField(blank=True, null=True, verbose_name='полное описание')),
                ('lat', models.FloatField(verbose_name='широта')),
                ('lon', models.FloatField(verbose_name='долгота')),
            ],
        ),
    ]
