# Generated by Django 4.1.3 on 2022-11-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_options_placeimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['image_order'], 'verbose_name': 'изображение места', 'verbose_name_plural': 'изображения места'},
        ),
        migrations.AlterUniqueTogether(
            name='placeimage',
            unique_together=set(),
        ),
    ]
